### ISSUE TITLE
Look into new CI

### ISSUE THREAD

**Issue by shymega** [input-leap/input-leap#1441]
This issue is to track the transition into a new CI platform, or to be
self-hosted, that can test older versions of macOS, Windows and Linux, for those
using older OSes.

The current CI is Azure Pipelines, which is soon discontinuing Windows Server
2016, which would mean our current CI configuration would break for Windows
releases.

AP also doesn't have Windows 11 as a build agent, or older Windows releases,
meaning new releases could break functionality on these older OSes. The same
goes for macOS and Linux.

**Comment by a5ehren** [comment]
I'm poking at this to learn GitHub Actions - is there some matrix of OS Support that you want to be able to test builds on for CI use?

Github Actions seem to make it pretty easy to spawn and use docker containers inside the ubuntu-latest image, so that will at least cover basically any Linux builds you want. 

I will admit to being completely ignorant of how building on MacOS and Windows works, though. I suspect that the images available in Actions for MacOS (10.15 and 11 for now, 12 coming soon) will cover the vast majority of users, but I have no clue what to do about Windows coverage.

**Comment by shymega** [comment]
Hi. I've been away from the project for a while, but I've tracked the PR discussion, and I really must stress that using two CI platforms isn't desirable for me. I'd rather have one. Azure is generally stable, the only issue is the agents. I know using GH Actions and Azure was discussed, but let's keep it KISS.

I don't really like the idea of more CI platforms to maintain. With regards to your PRs, let's discuss them here first, so we can iron out issues, think about the approach etc.

**Comment by luser** [comment]
Options for macOS cloud compute are thin on the ground, mostly because of Apple's draconian virtualization restrictions. GitHub Actions does have [an option to self-host runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners), so you could certainly acquire some mac minis and use them as runners for mac testing.

**Comment by shymega** [comment]
I wanted to come back to this. We now have GH Actions AND Azure Pipelines. They are both run on the same infrastructure, so I think we should move completely to GH Actions, and keep it simple. What's the point of two CIs? It's unnecessary. More complexity. I know @p12tic said to me he'd happily maintain both, but it's just such a waste of compute cycles, and adds very little to the project.

I want to move to one CI platform, and if GH Actions supports self-hosted runners, we could test on M1, and Windows 11.

Let's do this!

**Comment by p12tic** [comment]
github actions has broken before when Azure Pipelines worked and vice-versa. Having single provider means we won't be able to merge some PRs at all once the primary provider is down.

**Comment by shymega** [comment]
Sure, but it doesn't happen often. It just adds so much complexity, we don't need it. And let's face it, if we don't merge some PRs when the provider is down, is that mission-critical? They're both run by the same company, Microsoft. We have had PRs that can be pending for a while, so I don't think having the provider down temporarily is really a big issue.

**Comment by p12tic** [comment]
> Sure, but it doesn't happen often.

Windows 2019 build has been failing on Github Actions for couple of weeks now due to some upload issue. Fortunately we have Windows 2019 build on Azure Pipelines. Knowing that Azure Pipelines build succeeds lets me merge PRs without looking into why Github build failed.

So in the last several weeks: time saved due to multiple CI providers - ~10 minutes, time consumed: 0. I'd rather keep the configuration that saves me time.

**Comment by shymega** [comment]
OK, so that's not related to GH Actions at all. I've talked about Windows 2019 failing, and it's due to VS Studio. Only Windows 2016 passes, and that's all that is setup on AP. If we can fix Windows 2019, we can move completely to GH Actions. We have no need for Azure Pipelines now. I would like to hear other contributor's thoughts on it though...

**Comment by luser** [comment]
If there's anything here you could use some help with I'm interested in contributing. I'm a long-time user of Synergy and currently between jobs, so I have some free time to fill.

**Comment by shymega** [comment]
Yeah, you could help. I thought the bug was the VS Studio path being hardcoded, which I encountered before, but it's not. Looks like when artifacts are uploaded on Windows, there's a bug where if the target path is empty, it doesn't upload. I've pushed a branch to test, and I'll make a PR shortly.

There's no need for two CI workflows, they both use the same infrastructure (Azure), and it's a complete waste of CPU cycles to build twice.

Also, it means more maintenance, and confusion for new users. We don't need two.

**Comment by cardonator** [comment]
I'm an interested third party here, I would like to have an actively developed solution but don't really want to manually build input leap. I have to agree that having multiple pipelines is not a really great idea, though, and GHAS is free for open source so why not.

**Comment by shymega** [comment]
> I'm an interested third party here, I would like to have an actively developed solution but don't really want to manually build input leap. I have to agree that having multiple pipelines is not a really great idea, though, and GHA is free for open source so why not.

I think me and Povilas came to an agreement to keep both pipelines up, even if it is a bit overkill. What I would like GHA to do is to build with clang, for both X11 and Wayland (libei), and the current setup isn't perfect.

I can't log onto Azure DevOps right now, as my M365 account is business, and registered to my personal email, not GitHub email. So I'd rather use GHA.

**Comment by sithlord48** [comment]
Can we close this as done we have new CI now

**Comment by shymega** [comment]
Closed as fixed.
