### ISSUE TITLE
After starting, screen blanks after a short amount of idle time

### ISSUE THREAD

**Issue by brianjmurrell** [input-leap/input-leap#1625]
### What happened?

After starting Input Leap on the _Server_ (i.e. machine with the keyboard and mouse) the screen has started blanking (i.e. black screen) after only a very short "idle" time.

This feels like it might be the built-in X11 screen blanker or DPMS mechanism.  This is not the GNOME screensaver.  No password is required to clear it.  Simply touching a key or the mouse makes it go away.

It seems as if Input Leap has enabled the X11 built-in screen blanking utility in some way.  I'd like it disabled.  It's annoying to have the screen keep blanking every few 10s of seconds.

### Version

v2.4.0

### Git commit hash (if applicable)

e71fbbfe

### If applicable, where did you install Input Leap from?

https://copr.fedorainfracloud.org/coprs/brianjmurrell/input-leap/ which is a build of https://src.fedoraproject.org/rpms/input-leap/tree/rawhide.

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### What OS versions are you using?

Fedora 38 on both server and client although this is orthogonal to the client.

### Relevant log output

```shell
No log output when this happens.
```

**Comment by shymega** [comment]
We should probably make it configurable. Although, do we need it? I'd like to gauge support for defaults, so to anyone affected by this issue, react with 👍🏻 for 'make it enabled by default' and :-1: for 'make it disabled by default'. 'It' is the X11 blanking - does anyone know if Wayland has a similar mech?

**Comment by brianjmurrell** [comment]
I guess I'm not sure why Input Leap is even doing anything with the configuration of the screen blanking.  Surely however the user has already configured their X desktop is working for them.  Why muck with it?  It honestly doesn't feel related to the goal of Input Leap so it really shouldn't be modifying it IMHO.

**Comment by shymega** [comment]
No, I agree, it's out of scope.

**Comment by prahal** [comment]
Could it be the Advanced Input Leap settings "Synchronize screen savers" misbehave?
I find this setting of interest even if I do not use it nowadays.

@brianjmurrell could you check in input leap settings > "Configure Server" > tab "Advanced server settings" that "Synchronize screen savers" is unticked?
Could be IL misbehaves or that one of the other boxes triggers the screen saver (gnome has no screen saver for a long time, only a screen lock which could be disabled on your box, thus the screen saver trigger will only blank your screen).

You can check your current gnome blank delay with:
`gsettings get org.gnome.desktop.session idle-delay`

**Comment by brianjmurrell** [comment]
> @brianjmurrell could you check in input leap settings > "Configure Server" > tab "Advanced server settings" that "Synchronize screen savers" is unticked?

I have it ticked.

> You can check your current gnome blank delay with: `gsettings get org.gnome.desktop.session idle-delay`

```
uint32 240
```

That all said, I have not seen this in a long time.

**Comment by prahal** [comment]
> That all said, I have not seen this in a long time.

Have you switched from Xorg to Wayland? (I believe input-leap only ported input sharing, not screensaver sync, to Wayland).
It could also be the issue was with a buggy component that triggered input-leap screensaver synchronization when it should have not. If the issue is gone, out of downgrading or testing in VM it will be hard to sort out what was the buggy component. Could you give the desktop stack you used around the time the screensaver was broken and now that it is no more?
I believe Fedora 38 was Gnome 44, so it would have been Gnome Shell/Mutter 44 on both client and server. Which version do you have nowadays?



If on Xorg you might also want to paste Xorg's current setting (which gnome should have set, but better check) with `xset q` (mostly "Screen Saver:" and "DPMS (Display Power Management Signaling):" sections. (in fact, what matters to X11 is the xset value, gnome idle-delay is only applied to this X11 settings)

If the issue triggers again you then might want to try unticking "Synchronize screen savers" in input leap settings > "Configure Server" > tab "Advanced server settings"

**Comment by brianjmurrell** [comment]
> Have you switched from Xorg to Wayland?

No.

> Could you give the desktop stack you used around the time the screensaver was broken and now that it is no more?

Whatever Fedora was current at the time.  I am always on the most recent/current Fedora.

> Which version do you have nowadays?

Per above, Fedora 40.

Probably this was an anomaly and we can close it.  I can re-open it if I see it again.
