### ISSUE TITLE
CI should build 'Universal Binaries' for macOS (Intel + ARM64 (M1))

### ISSUE THREAD

**Issue by shymega** [input-leap/input-leap#1704]
I would like to see CI to use either GitHub-provided M1 runners for builds, or self-hosted M1 Macs (I believe @p12tic has one), so that we can produce 'Universal Binaries' for both Intel and ARM64 (M1) Mac machines.

This issue serves as a tracker:

- [ ] Make sure we use a compatible version of Qt for these builds, that supports compiling for ARM64 chips.
- [ ] Check that the OpenSSL dependency, and other dependencies (such as `gulrak-filesystem`) supports ARM64.
- [ ] (more...?)

We could also extend this to Windows and Linux ARM64 builders. But for now, the pressing issue is macOS.

**Comment by Cimbali** [comment]
With M1 runners, building for M1 should be out of the box.

I’ve explored [cross-compiling for M1 on current mac runners](https://github.com/input-leap/input-leap/commit/f31877c93af8a36be9b582834dbfb65f913704c7) which is somewhat more complex, as you need to run some tools that are part of the qt distribution (`uic`, `moc`, `lconvert`, etc.) which means the build needs access to both a host-architecture Qt and a cross-compiled Qt to link against. In the end, I got it to the point of correctly building for M1, but the libraries in the installer were not all of the right architecture.

Note that this approach downloads built M1 distributions of all libraries from homebrew, rather than re-compiling qt with cross-compiling support, which [I didn’t manage to get working](https://github.com/Cimbali/homebrew-qt5-macx-arm64). The [qt6 build system](https://www.qt.io/blog/qt-6-build-system) seems to simplify that process so I’d need to revisit.

**Comment by sithlord48** [comment]
While its true, All you need todo is use the CMake option `-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"` as stated above to build a universal binary. 

@Cimbali  you don't have to do anything like what you did in your test simply run the normal mac runner with the cmake option, it should "just work". You can use this action https://github.com/jurplel/install-qt-action to just install Qt from the normal sources so you don't need to build it. 

Your main issue is that Qt5 does not have a universal build, You will need to build with Qt6 for this to work.

Since I work alot with Qt I use the `macdeployQt` tool that comes with Qt to finalize my DMG file before cpack is run. 

I have not looked at how you all are doing the cmake deployment but if you are generating a Bundle and having the deploy tool from from cmake it may "just work" with out modification. Most of the items provided with os 12 + support universal so you may find its is not much of an issue.

**Comment by ann0see** [comment]
Even though a PR already exists, we (Jamulus development team) are also using Qt. So as reference, you can have a look at https://github.com/jamulussoftware/jamulus/tree/main/.github/autobuild - this also includes Debian ARM builds.

**Comment by shymega** [comment]
> Even though a PR already exists, we (Jamulus development team) are also using Qt. So as reference, you can have a look at https://github.com/jamulussoftware/jamulus/tree/main/.github/autobuild - this also includes Debian ARM builds.

Thanks for your input here. This is an interesting file to look at.
