### ISSUE TITLE
not working at macOS Catalina 10.15.7 (19H2026)

### ISSUE THREAD

**Issue by alexfguima** [input-leap/input-leap#2058]
### What happened?

did not work

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

package provided bit repository

### What OSes are you seeing the problem on? (Check all that apply)

macOS

### If applicable, are you using Wayland or X11?

no

### What OS versions are you using?

Mac OS Catalina 10.15.7 (19H2026)

**Comment by MatthewTheBird** [comment]
I'm having the same issue. I tried to install via Homebrew on macOS 10.15.7, but there are issues of compatibility with the different dependencies and everything there and this version of macOS.

So I then installed with the dmg that's provided in the release via GitHub and it doesn't even appear to do anything on the desktop and dock when launched. Through the Console, it seems to be running into code signing issues, so GateKeeper and System Integrity Protection kick in to quit the app before it can even launch.

I tried to sign it myself with `sudo codesign --force --deep --sign - /Applications/InputLeap.app`, which slightly changed the output in Console, but ultimately didn't change the outcome.

That's as far as I can really go with the troubleshooting and diagnostics. It would be great to use Input Leap on this version of macOS, but unless this issue is fixed (if it can be fixed) perhaps compatibility with macOS <= 10.15.x should be removed from the readme so people don't get frustrated by it not working on this version?

**Comment by shymega** [comment]
You can build with Qt 5.

To do so, clone Input Leap, checkout the latest tag (or download the source tarball), install Qt 5 on your Mac, and initialise CMake with the following arg: `-DQT_DEFAULT_MAJOR_VERSION=5` - it's Qt 6 by default, but this sets it to Qt 5.

Once you run `make` as per the wiki instructions, and a DMG is created, you should thus be able to install a working build.
